### PR TITLE
Added legend to the network map

### PR DESCRIPTION
**Pull request by shubh0107**
Hi Somesh,

I've added legend to the network map.
I've used the male images for all the 3 cases. However, it would be better if it shows just the color and not the gender in the legend, so that its more generic.

Let me know if you have such images.

### CODE REVIEW

**Comment by sibeshkar** [comment]
Hi, these are a little too big, are making the graph look cluttered. Consider a smaller design.

**Comment by shubh0107** [comment]
Hi, i've reduced the font size of the label and the size of the image.

**Comment by sibeshkar** [comment]
Just occurred to me - can you make this so that it acts as a legend for other nodes as well, depending on the filter selected. Like for city, state, foreign destination, local destination.

**Comment by shubh0107** [comment]
Yeah that thought crossed my mind too. Lemme get back with another commit.

**Comment by sibeshkar** [comment]
Can you merge from to latest master. The city cluster fixed so you can add legends for it.

**Comment by shubh0107** [comment]
Sure.

**Comment by shubh0107** [comment]
Have pushed again with the latest master code.

**Comment by sibeshkar** [comment]
Thanks. Looks good! Merging.

**Pull request merged**
