### PR TITLE
fix: Disable click action on disabled dates

### LINKED ISSUE #99: Date change issue
**Describe the bug**
Now only 23, 24, 25, 26 dates are highlighted and the record changes if we change the date but if the selected is of before 23 then the record is not changing.

**To Reproduce**
open the website and change the date.

**Expected behavior**
On changing dates before 23 it should either show the correct data or clear the map. Also freezing the dates before 23 will be a good option. 

**Screenshots**
Screenshot from 2020-03-26 20-21-32
Screenshot from 2020-03-26 20-21-39

**Desktop (please complete the following information):**
 - OS: ubuntu
 - firefox
 - 72.0.0

### PR DESCRIPTION
**Pull request by sampathBlam**
- Check for value of res.success
- If res.success is true, set the correct data to graph
- Else set an empty data set to cluster.
- Fixes #99

### CODE REVIEW

**Comment by sibeshkar** [comment]
I think a better solution to this issue would be to disable selection for unavailable dates. Do consider that, if not will merge this.

**Comment by sampathBlam** [comment]
Yup sure. Will do that.

**Comment by sampathBlam** [comment]
@sibeshkar : Done.

**Comment by sibeshkar** [comment]
Thanks!

**Pull request merged**
