### PR TITLE
[Loveneesh] #24 Add support to remove non connected edges in P2P filter

### PR DESCRIPTION
**Pull request by lovewithmind**
Add support to remove all leaf node in the graph to see only connected cases. This only works in P2P filter and is hidden in other filters.

This is a reference to #24 

Please let me know if you need any modifications.

### CODE REVIEW

**Comment by lovewithmind** [comment]
Attaching Screen Shot for reference

Screenshot 2020-03-26 at 6 34 44 AM

**Comment by sibeshkar** [comment]
Thanks. Can you make this for each filter? Label the checkbox : "Remove patient nodes without connections?" and checking it removes any nodes without an edge.

**Comment by lovewithmind** [comment]
Sure , can do that for other filter as well . But just wanted to know if it will make sense to have it in other filters as city , state and travel filter are already connected graphs.

**Comment by sibeshkar** [comment]
As in, it should just remove all unconnected nodes in one go for these filters as well.

**Comment by lovewithmind** [comment]
Ok sure will do the change for other filters as well

**Comment by lovewithmind** [comment]
It might not be possible to remove unconnected nodes in one go for all filters. As unconnected node in one graph might be a connected node in another graph with different filter. E.g node 45 is not connected in P2P filter but it is connected to city PUNE in city filter. 
Screenshot 2020-03-26 at 3 52 51 PM
Screenshot 2020-03-26 at 3 53 34 PM

So, if we want to remove all the people node no matter if it is connected to city or state . Then it can be done in one go for all filter.

What are your suggestions ?

**Comment by sibeshkar** [comment]
best option is to hide the edges on checking the box, unhide them on switching filters(reset).

**Comment by lovewithmind** [comment]
Seems like a good option.

**Comment by lovewithmind** [comment]
I have tried it in all the filter but as City and state is a connected graph it would not require this filter. So , It only make sense to have it in Person to Person filter. 

Raised #165 for the same

**Pull request closed without merging**
