### PR TITLE
[Loveneesh] Add support to remove non connected edges in P2P filter

### PR DESCRIPTION
**Pull request by lovewithmind**
Add support to remove all leaf node in the graph to see only connected cases. This only works in P2P filter and is hidden in other filters.

As City and State is always a connected graph I think it would not require this this filter.

This is a reference to #24 and #75

### CODE REVIEW

**Comment by sibeshkar** [comment]
just fixing travel filter, will then add this feature. Thanks!

**Comment by lovewithmind** [comment]
sure, Thanks!

**Comment by someshkar** [comment]
Hey @lovewithmind, really sorry on the delay in merging this, but can you resolve the merge conflicts and I'll merge it ASAP? This looks like the only viable solution to improving cluster performance at the moment, and I'd love to merge it very soon.

Moreover, it looks like it only works on the P2P filter? Can you make it work for the others too? For now though, just fix the merge conflicts and I'll merge this

**Comment by lovewithmind** [comment]
Hi @someshkar , I have resolved the merge conflict on the branch. You can merge it to master now.

**Pull request merged**
