### PR TITLE
Patient with id 251042 has no state/district/city attached so throwin…

### PR DESCRIPTION
**Pull request by saivinod440**
…g error while checking for city/state filter, Fixed by checking no state in getCityDistrictOrState method and same checking in addCities method

### CODE REVIEW

**Comment by saivinod440** [comment]
251047,251048,251049 these ids are not having any state info inorder to handle if no state the above fix will work without any code break which is happening now

**Comment by sibeshkar** [comment]
Thanks for pushing this. The error still seems to be happening for the travel filter. Can add a fix to that in this PR?

`Uncaught Error: Object argument required.`

**Comment by sibeshkar** [comment]
Ignore, I think travel filter is problem with the NLP api. Thanks for the fix.

**Comment by saivinod440** [comment]
Just now checked with travel as well this seems to be happening with travel if place_attributes object is not present currently we are checking if it's not null but if it is undefined it'll again block the code flow even if we are getting data from NLP API. I'll be fixing and create a pull request within an hour :)

**Pull request merged**
